services:
    oneup_contao.full_background_images.dca_helper:
        class: Oneup\ContaoFullBackgroundImagesBundle\Helper\Dca\DcaHelper
        public: true

    oneup_contao.full_background_images.fbi_helper:
        class: Oneup\ContaoFullBackgroundImagesBundle\Helper\FbiHelper
        public: true

    oneup_contao.full_background_images.runner:
        class: Oneup\ContaoFullBackgroundImagesBundle\Runner
        public: true
        arguments:
            - '@request_stack'
            - '@contao.routing.scope_matcher'
            - '@oneup_contao.full_background_images.fbi_helper'
        tags:
            - { name: contao.hook, hook: generatePage }
